name: mlflow-linear-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - mlflow
    - fastapi
    - uvicorn[standard]
    - pydantic
    - pyarrow
    - joblib
    - tqdm
    - cloudpickle>=2.2.1
    - typing-extensions>=4.7.1
    - dataclasses-json
